### ISSUE TITLE
Support custom components

### ISSUE THREAD

**Issue by rahearn** [icalendar/icalendar#142]
Both X prefixed and otherwise. Root problem for #136

**Comment by plehoux** [comment]
Before full-blown **support for custom components** would you accept a pull request that ignores those components instead of raising when parsing an invite?

Apple Calendar generated `.ics` can contain:

```
BEGIN:X-ICLOUD-PERINSTANCE
BEGIN:X-ICLOUD-PERUSER
```

Raising when encountering those make the parser quite fragile. I believe ignoring those components would be a better option. What do you think?

p.s. Thanks for your work.

**Comment by rahearn** [comment]
@plehoux I just added #232 to hopefully address this. Would you mind taking a look at it?
