### ISSUE TITLE
Recurring events not properly excluding deleted instances

### ISSUE THREAD

**Issue by extrajordanary** [icalendar/icalendar#168]
Example:
Say I have an event "Do a Thing", set to recur every Wed from Oct 5, 2016 until Dec 30, 2016
Then I delete just the very first instance that was on Oct 5 (through google calendar UI).

But the way that the deleted instances seem to work is that they don't add their date info to the EXDATE, so based on the recurrence rules, when I access `all_occurrences` I still get one for Oct 5th bc that's still listed as the recurring event's start date. Affects any events between the original start and end dates as far as I can tell. 

I haven't had much time yet to dive into the Google Calendar API more yet myself to see if I can work up a possible solution, but seems like it will require actually pulling the instances and checking their statuses instead of just relying on the recurrence rules (and then locally we were comparing to exclude those in the EXDATE).

**Comment by espen** [comment]
I don't understand, is this a problem with the iCalendar gem or the way Google Calendar produces their iCalendar-feed?

**Comment by stewartjohnson** [comment]
I think this gem is working correctly -- when you have an excluded instance in a recurring event there is an exdate property on the Icalendar::Event that is an array of DateTime/Date objects that list the excluded dates.

Just wish this gem provided an enumerable property of the event that would list all of the recurring event instances one by one rather than me having to monkeypatch it in. :-/

**Comment by rahearn** [comment]
@stewartjohnson Check out https://github.com/icalendar/icalendar-recurrence for a possible solution to occurrence expansion.

Closing this issue as it doesn't seem to relate to the icalendar gem.
