### ISSUE TITLE
How to create all-day events?

### ISSUE THREAD

**Issue by lindig** [icalendar/icalendar#71]
The documentation should include an example how to create an all-day event as this seems to have changed from the 1.x version. The following start/end is not recognized as several all-days events but maybe this is correct.

  DTSTART:20140209T000000
  DTEND:20140215T000000

**Comment by skbly7** [comment]
Hi, I just came across this topic, and would like to suggest change to wiki for addition of:
"The `dtstart` and `dtend` values should not be same, and in case of single day event, `dtend` value can be kept as next day's date."

Reference:
https://www.ietf.org/rfc/rfc2445.txt
For DTEND: "The value MUST be later in time than the value of the "DTSTART" property."

**Comment by rahearn** [comment]
@skbly7 made that change.

**Comment by MarioCambas** [comment]
This work for me 
DTSTART:20200312T000000
DTEND:20200312T240000
and shows all day after import it to windows 10 calendar

**Comment by Willardgmoore** [comment]
@MarioCambas the reason that worked for you is because you have the same start and stop times, but that the times are represented in timezones that are 24 hours apart. All day events would be expected to remain in the same time zone and begin on one day and end on another. 

I or someone on my team will be testing this in the next day or two using this gem and can confirm then.

**Comment by lindig** [comment]
@Willardgmoore the time after T is not a time zone offset but represents the time on that date. Do I think your explanation is not correct for why this works.
